.PHONY: clean All

All:
	@echo "----------Building project:[ ConstructorAndDestructors - Debug ]----------"
	@cd "ConstructorAndDestructors" && "$(MAKE)" -f  "ConstructorAndDestructors.mk"
clean:
	@echo "----------Cleaning project:[ ConstructorAndDestructors - Debug ]----------"
	@cd "ConstructorAndDestructors" && "$(MAKE)" -f  "ConstructorAndDestructors.mk" clean
